config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  get 'subjects/show'

  get 'subjects/new'

  get 'subjects/create'

  get 'subjects/edit'

  get 'subjects/update'

  get 'subjects/destroy'

  get 'timed_objects/index'

  get 'timed_objects/show'

  get 'timed_objects/new'

  get 'timed_objects/create'

  get 'timed_objects/edit'

  get 'timed_objects/update'

  get 'timed_objects/destroy'

  get 'schedule_days/index'

  get 'schedule_days/show'

  get 'schedule_days/new'

  get 'schedule_days/create'

  get 'schedule_days/edit'

  get 'schedule_days/update'

  get 'schedule_days/destroy'

  get 'schedule_days_controller/index'

  get 'schedule_days_controller/show'

  get 'schedule_days_controller/new'

  get 'schedule_days_controller/create'

  get 'schedule_days_controller/edit'

  get 'schedule_days_controller/update'

  get 'schedule_days_controller/destroy'

  root 'main_page#create'
  get 'main_page/create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :schedules

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  #Следующие типы привязок : 1) привязка к дням недели (пн => 1 ,...,вс =>7), например график работы какого либо учереждения
  #                         2) привязка к определённым датам , напимер расписание консультаций или экзаменов
  #                         3) привязка к неделям, напимер расписание занятий(напимер в 'Институте который я не хочу называть')
  #                         4) привязка к фазе луны и положению планет (в расширенной версии)
  validates :name, uniqueness: true
  has_many :schedule_days, inverse_of: :schedule
  has_and_belongs_to_many :user_groups
  #Нужно создать контроллеры для всего и на все действия REST, пока без пользовательских ограничений
end

app/models/schedule_day.rb
class ScheduleDay < ActiveRecord::Base
  belongs_to :schedule, inverse_of: :schedule_days
  has_and_belongs_to_many :timed_objects

  #  Нужно ввести свойство priority которое характеризует приоритет объекта описывающего день: 1- обычный объект; 2... - особые события,
  # из событий с одинаковым приоритетом (такой ситуации лучше постараться избежать на этапе валидации) выбирать первое, чем больше число тем выше приоритет

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :timed_object
end

app/models/timed_object.rb
class TimedObject < ActiveRecord::Base
  belongs_to :subject
  has_and_belongs_to_many :schedule_days
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_and_belongs_to_many :user_groups
  has_secure_password


end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  validates :name, uniqueness: true
  has_and_belongs_to_many :users
  has_and_belongs_to_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def create
    @main_page_schedule=Schedule.first
  end
end

app/controllers/schedule_days_controller.rb
class ScheduleDaysController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  #Вывод всех расписаний из базы данных (Название(с ссылкой) и Описание)
  def index
    @schedules = Schedule.all
  end

  #Отображение выбранного расписания (скорее всего сюда будет дописываться ограничение, или нет)
  def show
    @schedule = Schedule.find(params[:id])
  end

  #Подготовка к созданию нового расписания (пока только создание имени и описания)
  def new
    @schedule=Schedule.new
  end

  #Создание (обработка запроса POST)
  def create
    @schedule = Schedule.new (schedule_params)
    if @schedule.save
      redirect_to @schedule
    else
      render 'new'
    end
  end

  #Обновление расписания
  def edit
    @schedule=Schedule.find(params[:id])
  end

  def update
    @schedule=Schedule.find(params[:id])
    if @schedule.update (schedule_params)
      render 'edit'
    else
      render 'edit'
    end
  end

  #Удаление расписания
  def destroy

  end

  private
  def schedule_params
    params.require(:schedule).permit(:name, :description, :type_schedule)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])

      log_in user
      redirect_to root_url
    else
      flash[:danger] = 'Ты охуел' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/timed_objects_controller.rb
class TimedObjectsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/schedule_days_helper.rb
module ScheduleDaysHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # авторизует текущего пользователя
  def log_in user
    session[:user_id] = user.id
  end

  # Возвращает текущего пользователя
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Возвращает true если пользователь авторизован
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/timed_objects_helper.rb
module TimedObjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScheduleWebOrganizer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <% flash.each do |message_type, message| %>
      <div class="alert"<%= message_type %>><%= message %></div>
  <% end %>
  <% if logged_in? %>
      <div class="user-info-auth-panel">
        <%= link_to "Выйти из системы", logout_path, method: "delete" %>
      </div>
  <% else %>
      <div class="user-info-auth-panel">
        <%= link_to "Авторизоваться ", login_path %>
      </div>
  <% end %>
</header>
<%= yield %>
</body>
</html>

app/views/main_page/create.erb
<h1>Главная страница</h1>
<h2>Schedule : <%= @main_page_schedule.name %></h2>
<h3>Description : <%= @main_page_schedule.description %></h3>

<div class="schedule-table">
  <table>
    <tr>
      <% @main_page_schedule.schedule_days.each do |i| %>
          <th>day_<%= i.number %></th>
      <% end %>
    </tr>

    <tr>
      <% @main_page_schedule.schedule_days.each do |i| %>
          <td>
            <%= render partial: 'shared/timed_object_cell', locals: {timed_object_cell: i.timed_objects.first} %>
          </td>
      <% end %>
    </tr>

    <tr>
      <% @main_page_schedule.schedule_days.each do |i| %>
          <td>
            <%= render partial: 'shared/timed_object_cell', locals: {timed_object_cell: i.timed_objects.second} %>
          </td>
      <% end %>
    </tr>

  </table>
</div>

app/views/schedule_days/create.html.erb
<h1>ScheduleDays#create</h1>
<p>Find me in app/views/schedule_days/create.html.erb</p>

app/views/schedule_days/destroy.html.erb
<h1>ScheduleDays#destroy</h1>
<p>Find me in app/views/schedule_days/destroy.html.erb</p>

app/views/schedule_days/edit.html.erb
<h1>ScheduleDays#edit</h1>
<p>Find me in app/views/schedule_days/edit.html.erb</p>

app/views/schedule_days/index.html.erb
<h1>ScheduleDays#index</h1>
<p>Find me in app/views/schedule_days/index.html.erb</p>

app/views/schedule_days/new.html.erb
<h1>ScheduleDays#new</h1>
<p>Find me in app/views/schedule_days/new.html.erb</p>

app/views/schedule_days/show.html.erb
<h1>ScheduleDays#show</h1>
<p>Find me in app/views/schedule_days/show.html.erb</p>

app/views/schedule_days/update.html.erb
<h1>ScheduleDays#update</h1>
<p>Find me in app/views/schedule_days/update.html.erb</p>

app/views/schedules/_form_days_type_1.erb
<div class="form-edit-schedule-1">
  <table class="table table-bordered">
    <thead >
      <th>Понедельник</th>
      <th>Вторник</th>
      <th>Среда</th>
      <th>Четверг</th>
      <th>Пятница</th>
      <th>Суббота</th>
      <th>Воскресенье</th>
    </thead>
    <tr>

    </tr>
  </table>
</div>

app/views/schedules/_form_name_desc.erb
<div class="row">
  <div class="col-md-6  col-md-offset-3">

    <%= form_for(@schedule, html: {multipart: true, :class => 'pure-form-stacked'}) do |f| %>
        <%= f.label 'Название' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label 'Описание' %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.label 'Тип расписания' %>
        <%= f.select :type_schedule,
                     options_for_select([['Привязка к неделе', 1],
                                         ['Привязка к датам', 2],
                                         ['Привязка к номеру недели', 3]]),
                     class: 'form-control' %>

        <%= f.submit 'Сохранить', class: 'btn btn-primary' %>

    <% end %>

  </div>
</div>

app/views/schedules/edit.erb
<h1>Schedule editor.</h1>



<%= render 'form_name_desc' %>

<% case @schedule.type_schedule %>
<% when 1 %>
    <p> Type 1</p>
    <%= render 'form_days_type_1' %>
<% when 2 %>
    <p> Type 2</p>
    <%= render 'form_days_type_2' %>
<% when 3 %>
    <p> Type 3</p>
    <%= render 'form_days_type_3' %>
<% else %>
    <p> Another type</p>
<% end %>

app/views/schedules/index.erb
<h1>Schedules list</h1>
<% @schedules.each do |s| %>
    <div class="schedule-item-info">
      <b>Name: </b><p><%= link_to s.name, schedule_path(s) %></p>
      <b>Description: </b><p><%= s.description %> </p>
    </div>
<% end %>

app/views/schedules/new.erb
<% provide(:title, 'Новое расписание') %>
<%= render 'form_name_desc' %>

app/views/schedules/show.erb
<p>Schedule: <%= @schedule.name %></p>
<p>Description: <%= @schedule.description %></p>

app/views/shared/_timed_object_cell.erb
<table style="margin-right: 5px; margin-bottom: 5px; border: solid 1px green">
  <tr style="border: 1px solid black">
    <td rowspan="2" style="border: 1px solid black; padding: 2px"> <%= timed_object_cell.subject.name %></td>
    <td style="border: 1px solid black; padding: 2px">
      <%= timed_object_cell.timeBegin.strftime("%H:%M") %>
    </td>
  </tr>
  <tr style="border: 1px solid black">
    <td style="border: 1px solid black; padding: 2px">
      <%= timed_object_cell.timeEnd.strftime("%H:%M") %>
    </td>
  </tr>
</table>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/destroy.html.erb
<h1>Subjects#destroy</h1>
<p>Find me in app/views/subjects/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>

app/views/subjects/show.html.erb
<h1>Subjects#show</h1>
<p>Find me in app/views/subjects/show.html.erb</p>

app/views/subjects/update.html.erb
<h1>Subjects#update</h1>
<p>Find me in app/views/subjects/update.html.erb</p>

app/views/timed_objects/create.html.erb
<h1>TimedObjects#create</h1>
<p>Find me in app/views/timed_objects/create.html.erb</p>

app/views/timed_objects/destroy.html.erb
<h1>TimedObjects#destroy</h1>
<p>Find me in app/views/timed_objects/destroy.html.erb</p>

app/views/timed_objects/edit.html.erb
<h1>TimedObjects#edit</h1>
<p>Find me in app/views/timed_objects/edit.html.erb</p>

app/views/timed_objects/index.html.erb
<h1>TimedObjects#index</h1>
<p>Find me in app/views/timed_objects/index.html.erb</p>

app/views/timed_objects/new.html.erb
<h1>TimedObjects#new</h1>
<p>Find me in app/views/timed_objects/new.html.erb</p>

app/views/timed_objects/show.html.erb
<h1>TimedObjects#show</h1>
<p>Find me in app/views/timed_objects/show.html.erb</p>

app/views/timed_objects/update.html.erb
<h1>TimedObjects#update</h1>
<p>Find me in app/views/timed_objects/update.html.erb</p>